// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2wpVT_XXB33BMtcOG5YcjDgvSFRNEWpY',
    appId: '1:721947801421:web:71b3cc758ef45ff9536904',
    messagingSenderId: '721947801421',
    projectId: 'codigo-task-3bf50',
    authDomain: 'codigo-task-3bf50.firebaseapp.com',
    storageBucket: 'codigo-task-3bf50.appspot.com',
    measurementId: 'G-ECHQS2E4QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC26ryANi1oAxbVPevg2erW85fixewVTkk',
    appId: '1:721947801421:android:f09967213ddcbe17536904',
    messagingSenderId: '721947801421',
    projectId: 'codigo-task-3bf50',
    storageBucket: 'codigo-task-3bf50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnsnvHQxDPjgbLym9_TSRQcvdZ5A7liBQ',
    appId: '1:721947801421:ios:6a974ac512598439536904',
    messagingSenderId: '721947801421',
    projectId: 'codigo-task-3bf50',
    storageBucket: 'codigo-task-3bf50.appspot.com',
    iosBundleId: 'com.example.flutterFiretask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnsnvHQxDPjgbLym9_TSRQcvdZ5A7liBQ',
    appId: '1:721947801421:ios:6a974ac512598439536904',
    messagingSenderId: '721947801421',
    projectId: 'codigo-task-3bf50',
    storageBucket: 'codigo-task-3bf50.appspot.com',
    iosBundleId: 'com.example.flutterFiretask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2wpVT_XXB33BMtcOG5YcjDgvSFRNEWpY',
    appId: '1:721947801421:web:391717a8b89c31cb536904',
    messagingSenderId: '721947801421',
    projectId: 'codigo-task-3bf50',
    authDomain: 'codigo-task-3bf50.firebaseapp.com',
    storageBucket: 'codigo-task-3bf50.appspot.com',
    measurementId: 'G-CCJT144DXC',
  );
}
